server:
  servlet:
    context-path: /drive-doctor

spring:
  jpa:
    username: postgres
    password: password
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
